### ISSUE TITLE
Add a note

### ISSUE THREAD

**Issue by mhzawadi** [cameroncros/PrivatePeriodTracker#1]
Hello,

I passed this app to my wife and she likes it for the most part, but wants to add a note to an entry. Would that be possible?

**Comment by cameroncros** [comment]
I think this should be doable. I'll see what I can do

**Comment by mhzawadi** [comment]
thanks

**Comment by cameroncros** [comment]
Added notes for entries, but they are limited as you cannot edit them at the moment. If you want/need edit ability, I'll leave this issue open and will try get to that in the future. Notes coming in v1.4, release will probably take some time to roll out.

**Comment by mhzawadi** [comment]
fantastic, will let the wife know to look out for the update. If she's happy will close this

**Comment by mhzawadi** [comment]
Hello,

Adding notes is great, but we cant seem to view them. Could we have modal to see the entry or some other view of the entry please?

**Comment by cameroncros** [comment]
Right, that seems like an oversight. They are supposed to be listed when
you click the day, but that's not working for some reason. I'll fix it asap

**Comment by cameroncros** [comment]
Update is live, when you click the day you can now see the list of events
and the notes.

**Comment by mhzawadi** [comment]
update from the Boss, She's happy now. thanks fort your work, would love to send you some funds as a thinks. 

https://ko-fi.com/ is very quick to setup and could added to your repo data as a support link

**Comment by cameroncros** [comment]
I'm glad she's happy with the app.

No funds necessary, donate to a local women's charity if you must.

**Comment by mhzawadi** [comment]
Will do 😁
